// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjxflsuezufvgufbsnml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqeGZsc3VlenVmdmd1ZmJzbm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjI5NjUsImV4cCI6MjA2Nzc5ODk2NX0.RTUhA8q9DQpKn4Vx_RfusRlILSMhbfVn0YRXD3hifF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});